import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Account from "@/components/layout/account";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-r from-darkMainColor via-secondaryColor to-mainColor`}
      >
        <div className="container mx-auto">
          <div className="flex items-center gap-5 min-h-screen md:flex-nowrap flex-wrap">
            <Account />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
