import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Reem Ebrahim",
  description: "Generated by Reem Ebrahim",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased bg-black`}>
        <div className="container mx-auto">
          <div className="flex items-center gap-5 min-h-screen md:flex-nowrap flex-wrap">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
